TOP = ../..

FILES = SIM3C1x4 \
        SIM3C1x6 \
        SIM3C1x7 \
        SIM3L1x4 \
        SIM3L1x6 \
        SIM3L1x7 \
        SIM3L1x8 \
        SIM3U1x4 \
        SIM3U1x6 \
        SIM3U1x7 \

include $(TOP)/mk/svd2py.mk

