all:
	make -C arm $@
	make -C atmel $@
	make -C fujitsu $@
	make -C holtek $@
	make -C nordic $@
	make -C nxp $@
	make -C st $@

clean:
	-rm *.pyc
	make -C arm $@
	make -C atmel $@
	make -C fujitsu $@
	make -C holtek $@
	make -C nordic $@
	make -C nxp $@
	make -C st $@
