#!/usr/bin/python
# -----------------------------------------------------------------------------
"""

Convert x.svd to x.py.

x.svd is a CMSIS System View Description file describing a device.
x.py is the same information presented as *.py code useable by pycs.

"""
# -----------------------------------------------------------------------------

import os
import sys

import lxml.etree as ET

# -----------------------------------------------------------------------------

svd2py_version = 1
infile = ''
outfile = ''

# -----------------------------------------------------------------------------

def string_cleanup(s):
  """remove extra spaces and carriage returns from a string"""
  if s is None:
    return s
  return ' '.join([x.strip() for x in s.split()])

# -----------------------------------------------------------------------------

class svd_register(object):
  """class for an register"""
  def __init__(self):
    pass

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None

class svd_interrupt(object):
  """class for an interrupt"""
  def __init__(self):
    pass

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None


class svd_address_block(object):
  """class for an address block"""
  def __init__(self):
    pass

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None


class svd_peripheral(object):
  """class for peripheral attributes"""
  def __init__(self):
    pass

  def lookup_register(self, name):
    """lookup register by name"""
    for r in self.registers:
      if r.name == name:
        return r
    return None

  def lookup_address_block(self, usage):
    """lookup an address block by usage"""
    for a in self.addressBlock:
      if a.usage == usage:
        return a
    return None

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None

class svd_cpu(object):
  """class for cpu attributes"""
  def __init__(self):
    pass

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None

  def attribute_string(self, s, name):
    if self.__dict__.has_key(name):
      s.append("  '%s': '%s'," % (name, self.__dict__[name]))
    else:
      s.append("  # '%s': 'string'," % (name))

  def attribute_boolean(self, s, name):
    if self.__dict__.has_key(name):
      s.append("  '%s': %s," % (name, str(self.__dict__[name])))
    else:
      s.append("  # '%s': boolean," % (name))

  def attribute_integer(self, s, name):
    if self.__dict__.has_key(name):
      s.append("  '%s': %d," % (name, self.__dict__[name]))
    else:
      s.append("  # '%s': integer," % (name))


class svd_device(object):
  """class for device attributes"""

  def __init__(self):
    pass

  def lookup_peripheral(self, name):
    """lookup peripheral by name"""
    for p in self.peripherals:
      if p.name == name:
        return p
    return None

  def attribute(self, x):
    name, value = x
    if not value is None:
      object.__setattr__(self, name, value)

  def __getattr__(self, name):
    return None

  def attribute_string(self, s, name):
    if self.__dict__.has_key(name):
      s.append("  '%s': '%s'," % (name, self.__dict__[name]))
    else:
      s.append("  # '%s': 'string'," % (name))

  def attribute_header(self, s, name):
    if self.__dict__.has_key(name):
      s.append('%s: %s' % (name, str(self.__dict__[name])))

# -----------------------------------------------------------------------------

# identifierType = string
# stringType = string
# xs:Name = string
# cpuNameType = string
# revisionType = string
# endianType = string
# xs:boolean = boolean
# scaledNonNegativeInteger = integer

def get_string(node, tag, default = None):
  """Get the text string for the tag from the node"""
  try:
    return node.find(tag).text
  except AttributeError:
    return default

def get_integer(node, tag, default = None):
  text_value = get_string(node, tag, default)
  try:
    if text_value != default:
      text_value = text_value.strip().lower()
      if text_value.startswith('0x'):
        return int(text_value[2:], 16)  # hexadecimal
      elif text_value.startswith('#'):
        # TODO(posborne): Deal with strange #1xx case better
        #
        # Freescale will sometimes provide values that look like this:
        #   #1xx
        # In this case, there are a number of values which all mean the
        # same thing as the field is a "don't care".  For now, we just
        # replace those bits with zeros.
        text_value = text_value.replace('x', '0')[1:]
        is_bin = all(x in '01' for x in text_value)
        return int(text_value, 2) if is_bin else int(text_value)  # binary
      elif text_value.startswith('true'):
        return 1
      elif text_value.startswith('false'):
        return 0
      else:
        return int(text_value)  # decimal
  except ValueError:
    return default
  return default

def get_boolean(node, tag, default = None):
  n = get_integer(node, tag, default)
  if n is None:
    return default
  return n != 0

# -----------------------------------------------------------------------------

def string_node(node, tag, default = None):
  return (tag, get_string(node, tag, default))

def boolean_node(node, tag, default = None):
  return (tag, get_boolean(node, tag, default))

def integer_node(node, tag, default = None):
  return (tag, get_integer(node, tag, default))

# -----------------------------------------------------------------------------

def x_dash_y_string(s, n):
  """parse a string of the form %d-%d"""
  x = s.split('-')
  if len(x) != 2:
    return None
  try:
    a = int(x[0], 10)
    b = int(x[1], 10)
  except:
    return None
  if (b - a + 1) != n:
    # wrong length
    return None
  return (a, b)

# -----------------------------------------------------------------------------

class svd_parser(object):

  @classmethod
  def read_file(cls, path):
    return cls(ET.parse(path))

  def __init__(self, tree):
    self.tree = tree
    self.root = self.tree.getroot()

  def get_register(self, node):
    r = svd_register()
    r.attribute(integer_node(node, 'dim'))
    r.attribute(integer_node(node, 'dimIncrement'))
    r.attribute(string_node(node, 'dimIndex'))
    r.attribute(string_node(node, 'name'))
    r.attribute(string_node(node, 'displayName'))
    r.attribute(string_node(node, 'description'))
    r.description = string_cleanup(r.description)
    r.attribute(string_node(node, 'alternateGroup'))
    r.attribute(string_node(node, 'alternateRegister'))
    r.attribute(integer_node(node, 'addressOffset'))
    r.attribute(integer_node(node, 'size'))
    r.attribute(string_node(node, 'access'))
    r.attribute(string_node(node, 'protection'))
    r.attribute(integer_node(node, 'resetValue'))
    r.attribute(integer_node(node, 'resetMask'))
    r.attribute(string_node(node, 'dataType'))
    r.attribute(integer_node(node, 'resetMask'))
    r.attribute(string_node(node, 'modifiedWriteValues'))
    #<xs:element name="writeConstraint" type="writeConstraintType" minOccurs="0"/>
    r.attribute(string_node(node, 'readAction'))
    #<xs:element name="fields" type="fieldsType" minOccurs="0" maxOccurs="1"/>
    r.derivedFrom = node.get('derivedFrom')

    # fixup- turn dimIndex into a dim length list of strings
    if r.dim is not None:
      if r.dimIndex:
        # look for strings of the form "%d-%d"
        x = x_dash_y_string(r.dimIndex, r.dim)
        if x is not None:
          r.dimIndex = ['%d' % i for i in range(x[0], x[1] + 1)]
        else:
          assert False, 'unhandled dimIndex string %s' % r.dimIndex
      else:
        # Assume a simple 0..n index
        r.dimIndex = ['%d' % i for i in range(r.dim)]

    return r

  def get_address_block(self, node):
    block = svd_address_block()
    block.attribute(integer_node(node, 'offset'))
    block.attribute(integer_node(node, 'size'))
    block.attribute(string_node(node, 'usage'))
    return block

  def get_interrupt(self, node):
    i = svd_interrupt()
    i.attribute(string_node(node, 'name'))
    i.attribute(string_node(node, 'description'))
    i.description = string_cleanup(i.description)
    i.attribute(integer_node(node, 'value'))
    return i

  def get_peripheral(self, node):
    peripheral = svd_peripheral()
    peripheral.attribute(string_node(node, 'name'))
    peripheral.attribute(string_node(node, 'version'))
    peripheral.attribute(string_node(node, 'description'))
    peripheral.description = string_cleanup(peripheral.description)
    peripheral.attribute(string_node(node, 'alternatePeripheral'))
    peripheral.attribute(string_node(node, 'groupName'))
    peripheral.attribute(string_node(node, 'prependToName'))
    peripheral.attribute(string_node(node, 'appendToName'))
    peripheral.attribute(string_node(node, 'headerStructName'))
    peripheral.attribute(string_node(node, 'disableCondition'))
    peripheral.attribute(integer_node(node, 'baseAddress'))
    peripheral.addressBlock = [self.get_address_block(x) for x in node.findall('./addressBlock')]
    peripheral.interrupts = [self.get_interrupt(x) for x in node.findall('./interrupt')]
    peripheral.registers = [self.get_register(x) for x in node.findall('.//register')]
    peripheral.derivedFrom = node.get('derivedFrom')

    # fixup: if a register is "derivedFrom" another register, add a derived_from reference
    for r in peripheral.registers:
      if r.derivedFrom:
        for f in peripheral.registers:
          if f.name == r.derivedFrom:
            r.derived_from = f

    return peripheral

  def get_device(self):
    """return the device described by the svd file"""
    # cpu
    node = self.root.find('./cpu')
    cpu = svd_cpu()
    cpu.attribute(string_node(node, 'name'))
    cpu.attribute(string_node(node, 'revision'))
    cpu.attribute(string_node(node, 'endian'))
    cpu.attribute(boolean_node(node, 'mpuPresent'))
    cpu.attribute(boolean_node(node, 'fpuPresent'))
    cpu.attribute(boolean_node(node, 'fpuDP'))
    cpu.attribute(boolean_node(node, 'icachePresent'))
    cpu.attribute(boolean_node(node, 'dcachePresent'))
    cpu.attribute(boolean_node(node, 'itcmPresent'))
    cpu.attribute(boolean_node(node, 'dtcmPresent'))
    cpu.attribute(boolean_node(node, 'vtorPresent'))
    cpu.attribute(integer_node(node, 'nvicPrioBits'))
    cpu.attribute(boolean_node(node, 'vendorSystickConfig'))
    cpu.attribute(integer_node(node, 'deviceNumInterrupts'))
    cpu.attribute(integer_node(node, 'sauNumRegions'))
    #<xs:element name="sauRegionsConfig" minOccurs="0">

    # device
    node = self.root
    device = svd_device()
    device.attribute(string_node(node, 'vendor'))
    device.attribute(string_node(node, 'vendorID'))
    device.attribute(string_node(node, 'name'))
    device.attribute(string_node(node, 'series'))
    device.attribute(string_node(node, 'version'))
    device.attribute(string_node(node, 'description'))
    device.attribute(string_node(node, 'licenseText'))
    device.cpu = cpu
    device.attribute(string_node(node, 'headerSystemFilename'))
    device.attribute(string_node(node, 'headerDefinitionsPrefix'))
    device.attribute(integer_node(node, 'addressUnitBits'))
    device.attribute(integer_node(node, 'width'))
    device.peripherals = [self.get_peripheral(x) for x in self.root.findall('.//peripheral')]

    # fixup: if a peripheral is "derivedFrom" another peripheral, add a derived_from reference
    for p in device.peripherals:
      if p.derivedFrom:
        for f in device.peripherals:
          if f.name == p.derivedFrom:
            p.derived_from = f

    return device

# -----------------------------------------------------------------------------

class py_output(object):

  def __init__(self, fname, device):
    self.fname = fname
    self.device = device

  def emit_header(self, f):
    """emit the informational file header"""
    s = []
    s.append('"""')
    s.append('generated by svd2py version %d' % svd2py_version)
    s.append('')
    self.device.attribute_header(s, 'vendor')
    self.device.attribute_header(s, 'name')
    self.device.attribute_header(s, 'description')
    self.device.attribute_header(s, 'series')
    self.device.attribute_header(s, 'version')
    s.append('"""')
    s.append('from regs import fld, fld_set, reg32, reg16, reg8, regset, memio')
    f.write('%s\n' % '\n'.join(s))

  def emit_registers(self, f):
    s = []
    for p in self.device.peripherals:
      if p.derivedFrom and len(p.registers) == 0:
        continue
      if p.derivedFrom is None and len(p.registers) == 0:
        print('%s: (strange) peripheral %s is not derived and has no registers' % (self.device.name, p.name))
        continue
      if p.derivedFrom and len(p.registers):
        print('%s: (strange) peripheral %s is derived and has registers' % (self.device.name, p.name))
        continue
      s.append('r = []')
      for r in p.registers:
        r_from = r
        if r.derivedFrom is not None:
          r_from = p.lookup_register(r.derivedFrom)
        comment = (' # %s' % r.description, '')[r is None]
        ofs = r.addressOffset
        if r.dim is None:
          s.append("r.append(reg%d('%s', 0x%x))%s" % (r_from.size, r.name, ofs, comment))
        else:
          for i in range(r.dim):
            # atmel has indexed register name with a %s string - what about other vendors?
            name = r.name % r.dimIndex[i]
            s.append("r.append(reg%d('%s', 0x%x))%s" % (r_from.size, name, ofs + (i * r.dimIncrement), comment))
      s.append("%s_regs = regset('%s', r)" % (p.name, p.description))
      s.append('')
    f.write('%s\n' % '\n'.join(s))

  def emit_memmap(self, f):
    """emit the memory map"""
    s = []
    s.append('memmap = {')
    for p in self.device.peripherals:

      # handle derivedFrom peripherals
      p_from = p
      if p.derivedFrom is not None:
        p_from = self.device.lookup_peripheral(p.derivedFrom)

      adr_blk = p_from.lookup_address_block('registers')
      if adr_blk is not None:
        if len(p_from.addressBlock) > 1:
          print("%s: (info) peripheral %s ignoring non 'registers' address block" % (self.device.name, p.name))
        address = p.baseAddress + adr_blk.offset
        size = adr_blk.size
        comment = (' # %s' % p_from.description, '')[p_from.description is None]
        regs = ('%s_regs' % p_from.name, "'%s'" % p_from.description)[len(p_from.registers) == 0]
        s.append("  '%s': (0x%08x, 0x%x, %s),%s" % (p.name, address, size, regs, comment))
      else:
        print("%s: (error) peripheral %s has no 'registers' address block" % (self.device.name, p.name))

    s.append('}')
    s.append('')
    f.write('%s\n' % '\n'.join(s))

  def emit_vtable(self, f):
    """emit the vector table"""
    # get the interrupts - there maybe duplicates so we add them to a dictionary
    irqs = {}
    for p in self.device.peripherals:
      for i in p.interrupts:
        if irqs.has_key(i.value):
          # should be the same name
          assert irqs[i.value][0] == i.name
        else:
          irqs[i.value] = (i.name, i.description)
    # output them in sorted order
    s = []
    s.append('vtable = {')
    for i in sorted(irqs.keys()):
      (name, description) = irqs[i]
      comment = (' # %s' % description, '')[description is None]
      s.append("  %d: '%s',%s" % (i, name, comment))
    s.append('}')
    s.append('')
    f.write('%s\n' % '\n'.join(s))

  def emit_cpu(self, f):
    """emit the cpu parameters"""
    cpu = self.device.cpu
    s = []
    s.append('cpu = {')
    cpu.attribute_string(s, 'name')
    cpu.attribute_string(s, 'revision')
    cpu.attribute_string(s, 'endian')
    cpu.attribute_boolean(s, 'mpuPresent')
    cpu.attribute_boolean(s, 'fpuPresent')
    cpu.attribute_boolean(s, 'fpuDP')
    cpu.attribute_boolean(s, 'icachePresent')
    cpu.attribute_boolean(s, 'dcachePresent')
    cpu.attribute_boolean(s, 'itcmPresent')
    cpu.attribute_boolean(s, 'dtcmPresent')
    cpu.attribute_boolean(s, 'vtorPresent')
    cpu.attribute_integer(s, 'nvicPrioBits')
    cpu.attribute_boolean(s, 'vendorSystickConfig')
    cpu.attribute_integer(s, 'deviceNumInterrupts')
    s.append('}')
    s.append('')
    f.write('%s\n' % '\n'.join(s))

  def emit_device(self, f):
    """emit overall device information"""
    s = []
    s.append('device = {')
    self.device.attribute_string(s, 'name')
    self.device.attribute_string(s, 'vendor')
    self.device.attribute_string(s, 'series')
    self.device.attribute_string(s, 'version')
    s.append("  'vtable': vtable,")
    s.append("  'memmap': memmap,")
    s.append("  'cpu': cpu,")
    s.append('}')
    s.append('')
    f.write('%s\n' % '\n'.join(s))

  def emit(self):
    f = open(self.fname, 'w')
    self.emit_header(f)
    self.emit_registers(f)
    self.emit_vtable(f)
    self.emit_memmap(f)
    self.emit_cpu(f)
    self.emit_device(f)
    f.close()

# -----------------------------------------------------------------------------

def pr_err(*args):
  sys.stderr.write(' '.join(map(str,args)) + '\n')
  sys.stderr.flush()

def pr_usage(argv):
  pr_err('Usage: %s <input_file> <output_file>' % argv[0])

def error(msg, usage = False):
  pr_err(msg)
  if usage:
    pr_usage(sys.argv)
  sys.exit(1)

def Process_Options(argv):
  """process command line options"""
  global infile, outfile

  # get the input file
  if len(sys.argv) < 2:
    error('must specify input file', True)
  infile = sys.argv[1]
  if not os.path.exists(infile):
    error('%s: input file does not exist' % infile, True)

  # get the output file
  if len(sys.argv) < 3:
    error('must specify output file', True)
  outfile = sys.argv[2]

# -----------------------------------------------------------------------------

def main():
  Process_Options(sys.argv)
  parser = svd_parser.read_file(infile)
  device = parser.get_device()
  py_output(outfile, device).emit()

main()

# -----------------------------------------------------------------------------
